version: '3.5'
services:
  site_telzir:
    image: webdevops/php-apache:7.4
    volumes:
      - .:/var/www/html
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/html/public
    ports:
      - 8081:80
    depends_on:
      - db_telzir
  composer_telzir:
    container_name: backend_telzir
    image: composer
    volumes:
      - ./:/app
    command: composer update
  db_telzir:
    image: mysql:5.7
    ports:
      - "3306:3306"
    command: --init-file /data/application/dump.sql
    volumes:
      - ./dump/dump.sql:/data/application/dump.sql
      - dba:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=telzir
      - MYSQL_ROOT_PASSWORD=root
volumes:
  dba: